<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)dgt.tests.snk</AssemblyOriginatorKeyFile>
    <StaticAnalysisCodeType>Test</StaticAnalysisCodeType>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'dgt.power.tests'">
    <PackageReference Include="TUnit" Version="1.61.15" />
    <PackageReference Include="JetBrains.dotCover.Framework" Version="1.0.2" />
  </ItemGroup>
</Project>
