// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dgt.power.codegeneration.Templates.tsl
{
    using Microsoft.Xrm.Sdk.Metadata;
    using System;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EntityLightFormTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("/* eslint-disable */\n///<reference path=\"");

            this.Write(this.ToStringHelper.ToStringWithCulture(typingPath));

            #line default
            #line hidden
            this.Write("\" />\n\n// Entity ");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write(" FormContext for  Form \"");

            this.Write(this.ToStringHelper.ToStringWithCulture(formName));

            #line default
            #line hidden
            this.Write("\"\nexport interface ");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden

            this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(Sanitize(formName,true))));

            #line default
            #line hidden
            this.Write("FormContext extends Xrm.FormContext {\n    getAttribute(): Xrm.Attributes.Attribute[];\n    getAttribute<T extends Xrm.Attributes.Attribute>(attributeName: string): T;\n    getAttribute(attributeName: string): Xrm.Attributes.Attribute;\n    getAttribute(index: number): Xrm.Attributes.Attribute;\n\n    getControl(): Xrm.Controls.Control[];\n    getControl<T extends Xrm.Controls.Control>(controlName: string): T;\n    getControl(controlName: string): Xrm.Controls.Control;\n    getControl(index: number): Xrm.Controls.Control;\n\n");
 foreach(var attr in Filter(entityMetadata.Attributes))
{
		var attrType = GetTypeScriptTypes(attr);

            this.Write("    ");

            this.Write(this.ToStringHelper.ToStringWithCulture(Summary(GetLocalizedLabel(attr.Description),1)));

            #line default
            #line hidden
            this.Write("\n    getAttribute(name: '");

            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));

            #line default
            #line hidden
            this.Write("'): ");

            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyTypedAttributeType));

            #line default
            #line hidden
            this.Write(";\n    ");

            this.Write(this.ToStringHelper.ToStringWithCulture(Summary(GetLocalizedLabel(attr.Description),1)));

            #line default
            #line hidden
            this.Write("\n    getControl(name: '");

            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));

            #line default
            #line hidden
            this.Write("'): ");

            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyTypedControlType));

            #line default
            #line hidden
            this.Write(";\n");

} // End Attribute loop

            this.Write("}\n\n// Entity ");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write("\nexport const ");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write("Metadata = {\n  typeName: \"mscrm.");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.LogicalName));

            #line default
            #line hidden
            this.Write("\",\n  logicalName: \"");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.LogicalName));

            #line default
            #line hidden
            this.Write("\",\n  collectionName: \"");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.LogicalCollectionName));

            #line default
            #line hidden
            this.Write("\",\n  primaryIdAttribute: \"");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.PrimaryIdAttribute));

            #line default
            #line hidden
            this.Write("\",\n  attributeTypes: {\n");
 foreach(var attr in Filter(entityMetadata.Attributes))
{
		var attrName = Unique(CamelCase(Sanitize(attr.SchemaName)),"M"+entityMetadata.LogicalName);
		var attrType = GetTypeScriptTypes(attr);

            this.Write("    ");

            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));

            #line default
            #line hidden
            this.Write(": \"");

            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyType));

            #line default
            #line hidden
            this.Write("\",\n");

} // End Attribute loop

            this.Write("  }\n};\n\n// ");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write(" Attribute constants\nexport const enum ");

            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write("Attributes {\n");
 foreach(var attr in Filter(entityMetadata.Attributes))
{
		var attrName = Unique(CamelCase(Sanitize(attr.SchemaName)),"A"+entityMetadata.LogicalName);

            this.Write("    ");

            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));

            #line default
            #line hidden
            this.Write(" = \"");

            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));

            #line default
            #line hidden
            this.Write("\",\n");

} // End Attribute loop

            this.Write("}\n\n\n");
 foreach(var attr in Filter(entityMetadata.Attributes).Where(e => e.AttributeType == AttributeTypeCode.Picklist))
{
    var attrName = Unique(CamelCase(Sanitize(attr.SchemaName)),"PL"+entityMetadata.LogicalName);
		var options = ((PicklistAttributeMetadata)attr).OptionSet.Options;

            this.Write("// Enum ");

            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));

            #line default
            #line hidden
            this.Write("\nexport const enum ");

            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));

            #line default
            #line hidden
            this.Write("Code {\n    ");
 foreach(var option in options)
        {

            this.Write("    ");

            this.Write(this.ToStringHelper.ToStringWithCulture(Sanitize(CamelCase(GetLocalizedLabel(option.Label)))));

            #line default
            #line hidden
            this.Write(" = ");

            this.Write(this.ToStringHelper.ToStringWithCulture(option.Value));

            #line default
            #line hidden
            this.Write(",\n    ");

    } // End Option loop

            this.Write("}\n");

} // End Attribute loop

            this.Write("\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
