// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dgt.power.codegeneration.Templates.tsl
{
    using Microsoft.Xrm.Sdk.Metadata;
    using System;

    /// <summary>
    /// Class to produce the template output
    /// </summary>

    #line 1 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EntityLightTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("/* eslint-disable */\n///<reference path=\"");

            #line 4 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typingPath));

            #line default
            #line hidden
            this.Write("\" />\n\n// Entity ");

            #line 6 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write(" FormContext\nexport interface ");

            #line 7 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write("FormContext extends Xrm.FormContext {\n    getAttribute(): Xrm.Attributes.Attribute[];\n    getAttribute<T extends Xrm.Attributes.Attribute>(attributeName: string): T;\n    getAttribute(attributeName: string): Xrm.Attributes.Attribute;\n    getAttribute(index: number): Xrm.Attributes.Attribute;\n\n    getControl(): Xrm.Controls.Control[];\n    getControl<T extends Xrm.Controls.Control>(controlName: string): T;\n    getControl(controlName: string): Xrm.Controls.Control;\n    getControl(index: number): Xrm.Controls.Control;\n\n");

            #line 18 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
 foreach(var attr in Filter(entityMetadata.Attributes))
{
		var attrType = GetTypeScriptTypes(attr);


            #line default
            #line hidden
            this.Write("    ");

            #line 22 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Summary(GetLocalizedLabel(attr.Description),1)));

            #line default
            #line hidden
            this.Write("\n    getAttribute(name: '");

            #line 23 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));

            #line default
            #line hidden
            this.Write("'): ");

            #line 23 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyTypedAttributeType));

            #line default
            #line hidden
            this.Write(";\n    ");

            #line 24 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Summary(GetLocalizedLabel(attr.Description),1)));

            #line default
            #line hidden
            this.Write("\n    getControl(name: '");

            #line 25 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));

            #line default
            #line hidden
            this.Write("'): ");

            #line 25 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyTypedControlType));

            #line default
            #line hidden
            this.Write(";\n");

            #line 26 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"

} // End Attribute loop


            #line default
            #line hidden
            this.Write("}\n\n// Entity ");

            #line 31 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write("\nexport const ");

            #line 32 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write("Metadata = {\n  typeName: \"mscrm.");

            #line 33 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.LogicalName));

            #line default
            #line hidden
            this.Write("\",\n  logicalName: \"");

            #line 34 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.LogicalName));

            #line default
            #line hidden
            this.Write("\",\n  collectionName: \"");

            #line 35 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.LogicalCollectionName));

            #line default
            #line hidden
            this.Write("\",\n  primaryIdAttribute: \"");

            #line 36 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.PrimaryIdAttribute));

            #line default
            #line hidden
            this.Write("\",\n  attributeTypes: {\n");

            #line 38 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
 foreach(var attr in Filter(entityMetadata.Attributes))
{
		var attrName = Unique(CamelCase(Sanitize(attr.SchemaName)),"M"+entityMetadata.LogicalName);
		var attrType = GetTypeScriptTypes(attr);


            #line default
            #line hidden
            this.Write("    ");

            #line 43 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));

            #line default
            #line hidden
            this.Write(": \"");

            #line 43 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyType));

            #line default
            #line hidden
            this.Write("\",\n");

            #line 44 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"

} // End Attribute loop


            #line default
            #line hidden
            this.Write("  }\n};\n\n// ");

            #line 50 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write(" Attribute constants\nexport const enum ");

            #line 51 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityMetadata.SchemaName));

            #line default
            #line hidden
            this.Write("Attributes {\n");

            #line 52 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
 foreach(var attr in Filter(entityMetadata.Attributes))
{
		var attrName = Unique(CamelCase(Sanitize(attr.SchemaName)),"A"+entityMetadata.LogicalName);


            #line default
            #line hidden
            this.Write("    ");

            #line 56 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));

            #line default
            #line hidden
            this.Write(" = \"");

            #line 56 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));

            #line default
            #line hidden
            this.Write("\",\n");

            #line 57 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"

} // End Attribute loop


            #line default
            #line hidden
            this.Write("}\n\n\n");

            #line 63 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
 foreach(var attr in Filter(entityMetadata.Attributes).Where(e => e.AttributeType == AttributeTypeCode.Picklist))
{
    var attrName = Unique(CamelCase(Sanitize(attr.SchemaName)),"PL"+entityMetadata.LogicalName);
		var options = ((PicklistAttributeMetadata)attr).OptionSet.Options;


            #line default
            #line hidden
            this.Write("// Enum ");

            #line 68 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));

            #line default
            #line hidden
            this.Write("\nexport const enum ");

            #line 69 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));

            #line default
            #line hidden
            this.Write("Code {\n    ");

            #line 70 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
 foreach(var option in options)
        {


            #line default
            #line hidden
            this.Write("    ");

            #line 73 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sanitize(CamelCase(GetLocalizedLabel(option.Label)))));

            #line default
            #line hidden
            this.Write(" = ");

            #line 73 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(option.Value));

            #line default
            #line hidden
            this.Write(",\n    ");

            #line 74 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"

    } // End Option loop


            #line default
            #line hidden
            this.Write("}\n");

            #line 78 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"

} // End Attribute loop


            #line default
            #line hidden
            this.Write("\n");
            return this.GenerationEnvironment.ToString();
        }
    }

    #line default
    #line hidden
}
