// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dgt.power.codegeneration.Templates.tsl
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EntityLightTemplate : EntityLightTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("/* eslint-disable */\n///<reference path=\"");
            
            #line 3 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypingPath));
            
            #line default
            #line hidden
            this.Write("\" />\n\n// Entity ");
            
            #line 5 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.SchemaName));
            
            #line default
            #line hidden
            this.Write(" FormContext\nexport interface ");
            
            #line 6 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.SchemaName));
            
            #line default
            #line hidden
            this.Write("FormContext extends Xrm.FormContext {\n    getAttribute(): Xrm.Attributes.Attribute[];\n    getAttribute<T extends Xrm.Attributes.Attribute>(attributeName: string): T;\n    getAttribute(attributeName: string): Xrm.Attributes.Attribute;\n    getAttribute(index: number): Xrm.Attributes.Attribute;\n\n    getControl(): Xrm.Controls.Control[];\n    getControl<T extends Xrm.Controls.Control>(controlName: string): T;\n    getControl(controlName: string): Xrm.Controls.Control;\n    getControl(index: number): Xrm.Controls.Control;\n\n");
            
            #line 17 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
 foreach(var attr in Filter(EntityMetadata.Attributes))
{
		var attrType = GetTypeScriptTypes(attr);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 21 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Summary(GetLocalizedLabel(attr.Description),1)));
            
            #line default
            #line hidden
            this.Write("\n    getAttribute(name: '");
            
            #line 22 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));
            
            #line default
            #line hidden
            this.Write("'): ");
            
            #line 22 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyTypedAttributeType));
            
            #line default
            #line hidden
            this.Write(";\n    ");
            
            #line 23 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Summary(GetLocalizedLabel(attr.Description),1)));
            
            #line default
            #line hidden
            this.Write("\n    getControl(name: '");
            
            #line 24 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));
            
            #line default
            #line hidden
            this.Write("'): ");
            
            #line 24 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyTypedControlType));
            
            #line default
            #line hidden
            this.Write(";\n");
            
            #line 25 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"

} // End Attribute loop

            
            #line default
            #line hidden
            this.Write("}\n\n// Entity ");
            
            #line 30 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.SchemaName));
            
            #line default
            #line hidden
            this.Write("\nexport const ");
            
            #line 31 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.SchemaName));
            
            #line default
            #line hidden
            this.Write("Metadata = {\n  typeName: \"mscrm.");
            
            #line 32 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.LogicalName));
            
            #line default
            #line hidden
            this.Write("\",\n  logicalName: \"");
            
            #line 33 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.LogicalName));
            
            #line default
            #line hidden
            this.Write("\",\n  collectionName: \"");
            
            #line 34 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.LogicalCollectionName));
            
            #line default
            #line hidden
            this.Write("\",\n  primaryIdAttribute: \"");
            
            #line 35 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.PrimaryIdAttribute));
            
            #line default
            #line hidden
            this.Write("\",\n  attributeTypes: {\n");
            
            #line 37 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
 foreach(var attr in Filter(EntityMetadata.Attributes))
{
		var attrName = Unique(CamelCase(Sanitize(attr.SchemaName)),"M"+EntityMetadata.LogicalName);
		var attrType = GetTypeScriptTypes(attr);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 42 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));
            
            #line default
            #line hidden
            this.Write(": \"");
            
            #line 42 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrType.DefinitelyType));
            
            #line default
            #line hidden
            this.Write("\",\n");
            
            #line 43 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"

} // End Attribute loop

            
            #line default
            #line hidden
            this.Write("  }\n};\n\n// Attribute constants\nexport const enum ");
            
            #line 50 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityMetadata.SchemaName));
            
            #line default
            #line hidden
            this.Write("Attributes {\n");
            
            #line 51 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
 foreach(var attr in Filter(EntityMetadata.Attributes))
{
		var attrName = Unique(CamelCase(Sanitize(attr.SchemaName)),"A"+EntityMetadata.LogicalName);

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 55 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attrName));
            
            #line default
            #line hidden
            this.Write("= \"");
            
            #line 55 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.LogicalName));
            
            #line default
            #line hidden
            this.Write("\",\n");
            
            #line 56 "/Users/raaa/GitHub/DigitallPower/src/modules/dgt.power.codegeneration/Templates/tsl/EntityLightTemplate.tt"

} // End Attribute loop

            
            #line default
            #line hidden
            this.Write("}\n\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class EntityLightTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
