name: Build DGTP

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  integration-tests:
    name: Enable Integration Tests
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "DGTP_TESTS_INTEGRATION_RUN=TRUE" >> $GITHUB_ENV

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: "7.0.x"
      - run: dotnet test /p:CollectCoverage=true --verbosity normal

  check-licenses:
    name: Check ThirdPartyLibraries
    runs-on: ubuntu-latest     
    needs:
      - build
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3

  release:
    name: Semantic Release
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    runs-on: ubuntu-latest
    needs:
      - build
      - test
      - check-licenses
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: "7.0.x"
      - name: Install packages
        run: npm ci --no-fund
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: npx semantic-release