name: Build DGTP

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Cache Packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --no-restore
      
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    steps:
    - name: Run Tests
      env:
        DGTP_TESTS_INTEGRATION_CONNECTION: ${{ secrets.DGTP_TESTS_INTEGRATION_CONNECTION }}
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --settings tests/coverlet.runsettings

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: ${{ matrix.os }} Tests            
        path: tests/**/test-results.trx
        reporter: dotnet-trx

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test
    steps:
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.16
      if: matrix.os == 'ubuntu-latest'
      with:
        reports: 'tests/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'lcov'

    - name: publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coveragereport/lcov.info
    