name: Check DGTP

on:
  push:
    branches: [ "beta" ]
  pull_request:
    branches: [ "main", "beta" ]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Cache Packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --settings tests/coverlet.runsettings --blame-hang-timeout 3m

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: ${{ matrix.os }} Tests
        path: tests/**/test-results.trx
        reporter: dotnet-trx

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.19
      if: matrix.os == 'ubuntu-latest'
      with:
        reports: 'tests/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'lcov'

    - name: publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      if: matrix.os == 'ubuntu-latest'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coveragereport/lcov.info
