name: Coverage DGTP

on:
  workflow_run:
    workflows: ["Test DGTP"]
    types:
      - completed

jobs:
  coverage:
    name: Test (${{ matrix.os }})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Run Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=lcov.info --verbosity normal"

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.16
      if: success() || failure()   # run this step even if previous step failed
      with:
        reports: 'tests/**/lcov.info'
        targetdir: 'coveragereport'
        reporttypes: 'lcov'

    - name: Generate Code Coverage report
      uses: barecheck/code-coverage-action@v1
      if: success() || failure()   # run this step even if previous step failed
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        barecheck-api-key: ${{ secrets.BARECHECK_API_KEY }}
        lcov-file: "./coveragereport/lcov.info"
        send-summary-comment: true
        show-annotations: "warning"