name: Release DGTP

on:
  push:
    branches: [ "main", "beta" ]

jobs:
  release:
    name: Semantic Release
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - name: Install packages
        run: pnpm install
      - name: Materialize Signing Key
        id: write_sign_key_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'key.snk'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          AssemblyOriginatorKeyFile: ${{ steps.write_sign_key_file.outputs.filePath }}
        run: pnpm exec semantic-release
