name: Release DGTP

on:
  push:
    branches: [ "main", "beta" ]

jobs:
  release:
    name: Semantic Release
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install packages
        run: npm ci --no-fund
      - name: Materialize Signing Key
        id: write_sign_key_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'key.snk'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          AssemblyOriginatorKeyFile: ${{ steps.write_sign_key_file.outputs.filePath }}
        run: npx semantic-release
